# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171113_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='location',
            field=models.ImageField(upload_to=''),
        ),
    ]
